# Production docker-compose configuration
# Use: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  atscribe_db:
    image: postgres:17-alpine
    volumes:
      - atscribe_db_data:/var/lib/postgresql/data
      - /home/futureaiit/docker/atscribe/prosumeai_backup.sql:/docker-entrypoint-initdb.d/backup.sql:ro
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    command: postgres -p 5433 -c 'listen_addresses=*'
    networks:
      - atscribe_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -p 5433"]
      interval: 30s
      timeout: 10s
      retries: 5

  atscribe_app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SESSION_SECRET: ${SESSION_SECRET}
      COOKIE_SECRET: ${COOKIE_SECRET}
      SESSION_MAX_AGE: ${SESSION_MAX_AGE}
      COOKIE_SAMESITE: ${COOKIE_SAMESITE}
      DISABLE_SECURE_COOKIE: ${DISABLE_SECURE_COOKIE}
      TRUST_PROXY: ${TRUST_PROXY}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      VITE_API_URL: ${VITE_API_URL}
      VITE_APP_URL: ${VITE_APP_URL}
      ORIGIN_URL: ${ORIGIN_URL}
      BASE_URL: ${ORIGIN_URL}
      CORS_ORIGIN: ${CORS_ORIGIN}
    volumes:
      - /home/futureaiit/docker/atscribe/logs:/app/logs
      - /home/futureaiit/docker/atscribe/uploads:/app/server/uploads
    depends_on:
      - atscribe_db
    networks:
      - atscribe_net
      - proxy_default

volumes:
  atscribe_db_data:

networks:
  atscribe_net:
    driver: bridge
  proxy_default:
    external: true 