# Production docker-compose configuration
# Use: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  app:
    build:
      target: production
    restart: always
    environment:
      NODE_ENV: production
      # Security headers and settings
      TRUST_PROXY: "true"
      DISABLE_SECURE_COOKIE: "false"
      COOKIE_SAMESITE: "strict"
    # Remove pgAdmin in production
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    # Security: Remove volumes that aren't needed in production
    volumes:
      # Keep only essential volumes
      - ./public/images:/app/public/images
      - ./server/uploads:/app/server/uploads
      - ./logs:/app/logs

  db:
    restart: always
    # Don't expose database port in production (remove from ports)
    ports: []
    # Harden database configuration
    environment:
      POSTGRES_HOST_AUTH_METHOD: md5  # Require password authentication
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
        reservations:
          memory: 256M
          cpus: '0.1'

  # Remove pgAdmin service in production for security
  pgadmin:
    deploy:
      replicas: 0

# Add production-specific network configuration
networks:
  atscribe-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "prosumeai-prod" 