# Production docker-compose configuration
# Use: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  app:
    build:
      target: production
    restart: always
    environment:
      NODE_ENV: production
    # Remove pgAdmin in production
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  db:
    restart: always
    # Don't expose database port in production
    ports: []
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
        reservations:
          memory: 256M
          cpus: '0.1'

  # Remove pgAdmin service in production
  pgadmin:
    deploy:
      replicas: 0 